---

# ubuntu block
- block:
    - name: "Install MCPServer ext. deps. repo keys"
      apt_key:
        id: "{{ item.id }}"
        url: "{{ item.url }}"
        state: "present"
        validate_certs: "{{ item.validate_certs }}"
      with_items: "{{ MCPServer.osdeps_repokeys }}"
      when: 
        - "MCPServer.osdeps_repokeys"

    - name: "Add MCPServer ext. deps. repos"
      apt_repository:
        repo: "{{ item }}"
        state: "present"
      with_items: "{{ MCPServer.osdeps_repos }}"
      when:  
        - "MCPServer.osdeps_repos"

    - name: "Install MCPServer ext. package deps."
      apt:
        pkg: "{{ item['name'] }}"
        state: "{{ item['state'] }}"
      with_items: "{{ MCPServer.osdeps_packages }}"
      when:
        - "MCPServer.osdeps_packages"

  when:
    - ansible_distribution == "Ubuntu"

# Centos/RH block 
- block: 
    - name: "Add MCPServer ext. deps. repos (RH/CentOS)"
      yum_repository:
        name: "{{ item['name'] }}"
        description: "{{ item['description'] }}"
        baseurl: "{{ item['baseurl'] }}"
        gpgcheck: "{{ item['gpgcheck']}}"
        enabled: "{{ item['enabled']}}"
      with_items: "{{ MCPServer.osdeps_repos }}"
      when:
        - MCPServer.osdeps_repos

    - name: "Install MCPServer ext. package deps. (RH/CentOS)"
      yum: 
        name: "{{ item['name'] }}"
        state: "{{ item['state'] }}"
      with_items: "{{ MCPServer.osdeps_packages }}  "
      when:
        - MCPServer.osdeps_packages is defined and MCPServer.osdeps_packages 

    - name: "Install MCPServer ext. package deps. (2) (RH/CentOS)"
      yum: 
        name: "{{ item['name'] }}"
        state: "{{ item['state'] }}"
      with_items: "{{ MCPServer.osdeps_packages_2 }}  "
      when:
        - MCPServer.osdeps_packages_2 is defined and MCPServer.osdeps_packages_2 

    - name: "Install MCPServer ext. package deps. (3) (RH/CentOS)"
      yum: 
        name: "{{ item['name'] }}"
        state: "{{ item['state'] }}"
      with_items: "{{ MCPServer.osdeps_packages_3 }}  "
      when:
        - MCPServer.osdeps_packages_3 is defined and MCPServer.osdeps_packages_3 

  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
  

